# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
      open-pull-requests-limit: 10
      commit-message:
          prefix: 'deps'
      # Enable auto-merge for all dependency updates
      allow:
          - dependency-type: all
      # Set auto-merge strategy (squash, merge, or rebase)
      commit-message:
          prefix: "deps"
