name: Auto Merge Dependabot PR

on:
    workflow_run:
        workflows: ['Deploy'] # <-- your deployment workflow name
        types:
            - completed

jobs:
    automerge:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Auto-merge Dependabot PRs
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
                  merge-method: squash
